language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12.18.2'
git:
  depth: 3
script:
  - yarn build
notifications:
  slack: viuture:ScNNleTkjp7tSMLYHmPlSB20
  email:
    recipients:
      - josephsiul15@gmail.com
      - luischg11@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: 'Deploy del proyecto'
  on:
    branch: master